services:
  - type: web
    name: aerolive
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: AVIATIONSTACK_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20
